### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Notes:
1.Thaumic Palmistry didn't get translation as the mod name. This will be discussed soon.
2.I use Lorem ipsum thing to fill the page context of focus: thaumeter and arcane furnace temporarily. This will be removed as soon as there is actual page context.
Thanks for understading!

### CODE REVIEW

**Comment by TheVizzy** [comment]
Good job!

**Comment by TheVizzy** [comment]
I will add you to Credits.

**Comment by 3TUSK** [comment]
Thanks!

**Comment by TheVizzy** [comment]
Tomorrow will be new update with work furnace!

**Pull request merged**
